### ISSUE TITLE
Configurable Port and Host

### ISSUE THREAD

**Issue by mohmadhabib** [chinmaykrishnroy/YouTubeDownloader#2]
Add ability to configure Port and Host

**Comment by chinmaykrishnroy** [comment]
Fixed for v1.2, you can set the port in the variable declaration section. If you want to change the port then in the last line 'app.run(debug=False)', add a parameter 'port' to the run method and set the port. For example, if you want to change the default port to 5123, you can change 'app.run(debug=False)' to 'app.run(debug=False, port=5123)'. Be sure to modify the redirect link of the webbrowser to open the corresponding port that you set as the port for the application.

**Comment by chinmaykrishnroy** [comment]
Fixed it, just one thing to mention if you are changing the host to '0.0.0.0' then it will run on all addresses but to access the application you still have to use localhost or the IPv4 for the device running the flask application. For example, you may get something like:
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5005
 * Running on http://192.168.xxx.xxx:5005
